SET IDENTITY_INSERT [dbo].[Article] ON
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (1, N'Les 3 mousquetaires', 10.5, N'http://placehold.it/200', N'Le roman raconte les aventures d''un Gascon impécunieux de 18 ans, d''Artagnan, venu à Paris pour faire carrière dans le corps des mousquetaires. Il se lie d''amitié avec Athos, Porthos et Aramis, mousquetaires du roi Louis XIII. Ces quatre hommes vont s''opposer au premier ministre, le cardinal de Richelieu et à ses agents, dont le comte de Rochefort et la belle et mystérieuse Milady de Winter, pour sauver l''honneur de la reine de France Anne d''Autriche.', 1, 1, 1, 3.5, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (2, N'Miles Davis', 15, N'http://placehold.it/200', N'Les meilleurs chansons de Miles Davis.', 0, 2, 5, 6.25, 4)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (3, N'GhostBusters', 18, N'http://placehold.it/200', N'Peter, Raymond et Egon effectuent des recherches sur la parapsychologie. Virés par le Doyen de la faculté, ils décident de fonder une société destinée à chasser les revenants. Son nom : S.O.S. Fantômes. Le succès frappe tant et si bien à leur porte qu''ils en sont bientôt à travailler à la chaîne.', 1, 3, 10, 5.5, 3)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (14, N'Les malheurs de sophie', 5, N'http://placehold.it/200', N'L''action se déroule dans un château de la campagne française du Second Empire où Sophie habite avec ses parents M. et Mme de Réan.
Curieuse et aventureuse, elle commet bêtise sur bêtise avec la complicité critique de Paul, son cousin, qui est bon et qui tente de lui montrer le droit chemin. Elle a pour amies Camille et Madeleine de Fleurville, des petites filles modèles qu''elle peine à imiter.', 0, 4, 1, 1.75, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (15, N'Les tontons flingeurs', 12.5, N'http://placehold.it/200', N'Sur son lit de mort, le Mexicain fait promettre à son ami d''enfance, Fernand Naudin, de veiller sur ses intérêts et sa fille Patricia. Fernand découvre alors qu''il se trouve à la tête d''affaires louches dont les anciens dirigeants entendent bien s''emparer. Mais, flanqué d''un curieux notaire et d''un garde du corps, Fernand impose d''emblée sa loi. Cependant, le belle Patricia lui réserve quelques surprises ! ', 1, 5, 10, 4.5, 2)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (16, N'Le c++ pour les nuls', 24, N'http://placehold.it/200', N'Une lecture adaptée pour les concepteurs développeurs!', 1, 6, 13, 7.5, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (17, N'Oh my god ma base de données!!!', 3, N'http://placehold.it/200', N'Le jour où j''ai détruit la base de données du projet SEBO. :-(', 1, 7, 17, 0.75, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (18, N'Bad Boys', 20.5, N'', N'Mike Lowrey est un séducteur invétéré, célibataire, tandis que Marcus Burnett est un homme rangé, marié et père de famille. Ils sont à la fois collègues, policiers à Miami, et amis. Avec toutefois des méthodes d''investigation radicalement opposées, ce qui rend parfois leur relation explosive.
Cent kilos d''héroïne pure sont dérobés dans les locaux de la brigade des stupéfiants de Miami, provoquant la colère du capitaine Howard. Les agents de la police de Miami ont 72 heures pour retrouver les coupables. Au même moment, la meilleure amie de Mike Lowrey est assassinée lors d''un règlement de compte entre criminels. Une jeune femme présente sur le lieu du crime parvient à s''échapper et prend contact avec la police. En tant que témoin, Julie Mott ne veut avoir à faire qu''à Mike et personne d''autre. Celui-ci étant indisponible, c''est Marcus qui se rend chez elle en se faisant passer pour son collègue. Les deux hommes vont ainsi échanger leurs identités pendant la durée de l''enquête.', 0, 8, 11, 7.5, 3)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (20, N'Mongo db pour les bébés.', 20, N'http://placehold.it/200', N'Livre très intéressant...', 1, 10, 17, 7.5, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (21, N'Léon', 10, N'http://placehold.it/200', N'Un tueur à gages répondant au nom de Léon prend sous son aile Mathilda, une petite fille de douze ans, seule rescapée du massacre de sa famille. Bientôt, Léon va faire de Mathilda une "nettoyeuse", comme lui. Et Mathilda pourra venger son petit frère... ', 1, 11, 11, 2, 3)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (22, N'Usual suspects', 10, N'http://placehold.it/200', N'Une légende du crime contraint cinq malfrats à aller s''acquitter d''une tâche très périlleuse. Ceux qui survivent pourront se partager un butin de 91 millions de dollars. ', 1, 12, 9, 3, 2)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (19, N'Best Of Céline Dion', 20.5, N'http://placehold.it/200', N'Le meilleur des chansons de Céline Dion, on a bien cherché, du coup on a mis un album de Kaaris.
C''est pas mieux!', 1, 9, 7, 7.5, 4)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (25, N'Okou Gnakouri', 8.99, N'', N'Avec son nouvel album Okoou Gnakouri, on retrouve le Kaaris de Or Noir, à la fois drôle et aux punchlines fracassantes

. Kaaris a le sourire depuis qu’il a goûté aux joies de la paternité.
 
Il est plus décidé que jamais à conserver son titre de roi de la Trap. 

Entre la musique et le cinéma, Kaaris est bien présent sur le devant de la scène. 

Pour son nouvel album, il s’est entouré de plusieurs producteurs : Double X, Mr Punisher, Blackstars, Fushubi, AriBeatz, Therapy…

 On y retrouve également deux grosses collaborations : Gucci Mane et Kalash Criminel.', 1, NULL, 19, 0, 4)
SET IDENTITY_INSERT [dbo].[Article] OFF
