SET IDENTITY_INSERT [dbo].[Article] ON
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (1, N'Les 3 mousquetaires', 20, N'kaaris.png', N'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consectetur volutpat neque, a cursus nunc iaculis et. In lobortis, ante ullamcorper ultricies eleifend, turpis erat volutpat tellus, non varius lorem metus non turpis. Proin dapibus neque nibh, ut tempor ante eleifend eu. Duis ut arcu ac dolor porttitor pharetra id a erat. Maecenas porttitor condimentum efficitur. Mauris maximus purus sit amet dui molestie dignissim. Quisque lorem erat, interdum at est eu, hendrerit luctus elit.', 1, 1, 3, 1, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (2, N'Miles Davis', 20, N'kaaris.png', N'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consectetur volutpat neque, a cursus nunc iaculis et. In lobortis, ante ullamcorper ultricies eleifend, turpis erat volutpat tellus, non varius lorem metus non turpis. Proin dapibus neque nibh, ut tempor ante eleifend eu. Duis ut arcu ac dolor porttitor pharetra id a erat. Maecenas porttitor condimentum efficitur. Mauris maximus purus sit amet dui molestie dignissim. Quisque lorem erat, interdum at est eu, hendrerit luctus elit.', 0, 5, 5, 2, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (3, N'Ghostbusters', 25, N'kaaris.png', N'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut consectetur volutpat neque, a cursus nunc iaculis et. In lobortis, ante ullamcorper ultricies eleifend, turpis erat volutpat tellus, non varius lorem metus non turpis. Proin dapibus neque nibh, ut tempor ante eleifend eu. Duis ut arcu ac dolor porttitor pharetra id a erat. Maecenas porttitor condimentum efficitur. Mauris maximus purus sit amet dui molestie dignissim. Quisque lorem erat, interdum at est eu, hendrerit luctus elit.', 1, 10, 10, 4, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (14, N'Les 3 mousquetaires', 12.5, NULL, NULL, 1, NULL, 10, 1, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (15, N'Les 3 petits cochons', 12.5, NULL, NULL, 1, NULL, 1, 2, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (16, N'Les 3 cloches', 12.5, NULL, NULL, 1, NULL, 1, 2, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (17, N'Les 3 vallées', 12.5, N'kaaris.png', NULL, 1, NULL, 1, 5, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (18, N'Les 3 soleils', 12.5, N'kaaris.png', NULL, 0, NULL, 1, 5, 1)
INSERT INTO [dbo].[Article] ([Reference], [LibelleArticle], [Prix], [PhotoArticle], [DescriptionArticle], [Reapprovisionnable], [IdStock], [IdGenre], [PrixAchat], [IdFournisseur]) VALUES (19, N'Best of Céline', 20, N'', N'', 1, NULL, 7, 3.5, 2)
SET IDENTITY_INSERT [dbo].[Article] OFF
